### ISSUE TITLE
antfu/top-level-function

### ISSUE THREAD

**Issue by transtone** [antfu/eslint-config#178]
### Clear and concise description of the problem

it says, `Top-level functions should be declared with function keyword`

why? I think using hoisting to break the function declare order is not a good habit.

### Suggested solution

`should be` -> `may be`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It's my **opinionated** config.

**Comment by antfu** [comment]
For consistency. And `function` keyword is more semantically readable/distinguishable. I consider top-level arrow function is a bad practice.

**Comment by so1ve** [comment]
Out of topic: I personally use arrow functions for those functions which have a return statement only, and function declarations for the rest. I have a rule @so1ve/function-style https://github.com/so1ve/eslint-config, which enforces function style but it might break the functionality due to "no-use-before-define". However I seldom met this issue because I always declare functions before they are used.
