### ISSUE TITLE
Use the entire `recommended`  config from unicorn 

### ISSUE THREAD

**Issue by fregante** [antfu/eslint-config#595]
### Clear and concise description of the problem

Unicorn has 100+ super useful rules, I was a bit disappointed to see that only a handful are enabled here:

https://github.com/antfu/eslint-config/blob/1d62059716d3aa2d757a8efc350125d4004ce308/src/configs/unicorn.ts#L11-L37

### Suggested solution

I think this config can just repackage the recommended config, and only disable/customize what you disagree with:

https://github.com/sindresorhus/eslint-plugin-unicorn#preset-configs-eslintconfigjs

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
The reason I tried to inline rules instead of using configs is that I want have more control over which rules to enable and don't want to get extra rules to sneak in when updating dependencies. 

I just checked, and I think the recommended rules are way too far to my liking; I don't think I will use the recommended ones directly. I will re-evaluate each and enable as many as possible. Meanwhile, feel free to bring up the discussion of each rule to see if we could enable them.

**Comment by fregante** [comment]
> feel free to bring up the discussion of each rule

The reason why I use shared configs is specifically to avoid having to research and customize each rule from each plugin. I'll have to load unicorn directly I suppose.

**Comment by antfu** [comment]
a4625b2 adds the option for you to enable all recommended rules if you want to https://github.com/antfu/eslint-config/commit/a4625b27b485fe4fd85488d842a4cc53431ff910#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410a

**Comment by fregante** [comment]
Ohh I didn't see that first line! Thank you 🙏
